In [1]:
import numpy as np

인덱싱
  - 파이썬 리스트와 동일한 개념으로 사용
  - ,를 사용하여 각 차원의 인덱스에 접근 가능



  - 1차원 벡터 인덱싱

In [4]:
x = np.arange(10)
print(x) 

[0 1 2 3 4 5 6 7 8 9]


In [6]:
x[0]    # 첫 번째 원소를 가져옴

0

In [8]:
x[-1]   # 마지막 원소를 가져옴

9

In [10]:
x[3]    # 네 번째 원소를 가져옴

3

In [11]:
x[3] = 100
print(x)

[  0   1   2 100   4   5   6   7   8   9]


* 2차원 행렬 인덱싱

In [13]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
x[0]

array([0, 1, 2, 3, 4])

In [16]:
x[1]

array([5, 6, 7, 8, 9])

In [17]:
x[0, 2]

2

In [18]:
x[1, 2]

7

In [19]:
x[1, -1]

9

  - 3차원 텐서 인덱싱

In [21]:
x = np.arange(36).reshape(3,4,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [22]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
x[1]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [26]:
x[1, 2]   # 크기가 3인 벡터를 가져옴

array([18, 19, 20])

In [28]:
x[1, 2, 1]

19

#### 슬라이싱
  - 리스트, 문자열 slicing과 동일한 개념으로 사용
  - ,를 사용하여 각 차원 별로 슬라이싱 가능(인덱싱과 달리 차원 변화 없음)

  - 1차원 벡터 슬라이싱

In [30]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [32]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

  - 2차원 행렬 슬라이싱

In [33]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [34]:
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [35]:
x[:, :2]

array([[0, 1],
       [5, 6]])

In [36]:
x[0, :2]    # 인덱싱은 차원이 한차원 줄어듬

array([0, 1])

In [37]:
x[:1, :2]

array([[0, 1]])

  - 3차원 텐서 슬라이싱

In [40]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [41]:
x[:1, :2, :]    # 슬라이싱으로 가져옴 (차원은 유지됨)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [42]:
x[0, :2, :]   # 인덱싱으로  가져올 때는 한 차원 줄어듬

array([[0, 1, 2],
       [3, 4, 5]])