In [ ]:
import numpy as np

#### ravel, np.ravel()
  - 다차원 배열을 1차원으로 변경
  - 'order' 파라미터
    - 'C' - row 우선 변경
    - 'F' - column 우선 변경

In [ ]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.ravel(x, order= 'C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.ravel(x, order= 'F')   # 값이 커지는 기준이 열임

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [ ]:
x = np.arange(15).reshape(3, 5)   # 행을 기준으로 값이 커짐
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
temp = x.ravel()
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
temp[0] = 100
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


#### flatten
  - 다차원 배열을 1차원으로 변경
  - ravel과의 차이점 
    - copy를 생성하여 변경함
    - 원본 데이터가 아닌 복사본을 반환
  - 'order' 파라미터
    - 'C' - row 우선 변경
    - 'F' - column 우선 변경

In [22]:
y = np.arange(15).reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [23]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
t2 = y.flatten()
print(t2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
t2[0] = 100
print(t2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [28]:
t2 = y.flatten(order='C')
print(t2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [29]:
t3 = y.flatten(order='F')
print(t3)

[ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]


In [31]:
x = np.arange(30).reshape(2,3,5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [32]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### reshape() 함수
  - array의 shape을 다른 차원으로 변경
  - 주의할 점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
  - 사례) 
    - 이미지 데이터 벡터화
      - 이미지는 기본적으로 2차원 혹은 3차원 (RGB)이지만 데이터 트레이닝을 위해 1차원으로 변경하여 사용됨

In [33]:
x = np.arange(36)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [34]:
print(x.shape)    # 1차원임

(36,)


In [35]:
print(x.ndim)   # 차원

1


In [37]:
y = x.reshape(6, 6)
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [38]:
y = x.reshape(-1,6)   # 6행 6열로 바꿈
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [39]:
y = x.reshape(6,-1)   # 6행 6열로 바꿈
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [40]:
# x.reshape(6,5)    # 크기가 맞지 않으면 에러남

In [41]:
y = x.reshape(6,6)
print(y.shape)
print(y.ndim)

(6, 6)
2


In [43]:
y = x.reshape(3, 3, 4)
print(y)
print(y.shape)
print(y.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
(3, 3, 4)
3


In [45]:
k = x.reshape(3, 3, -1)   # 나머지 2개가 고정되면 하나는 유추할 수 있으니 -1로 설정해도 됨
print(k)
print(k.shape)
print(k.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
(3, 3, 4)
3
