In [1]:
import numpy as np

#### numpy documentation
  - [numpy 공식 문서 링크](https://numpy.org/doc/stable/reference/)
  - numpy에서 제공되는 함수등에 대한 문서

In [3]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)   # 행렬 크기가 다르면 연산 에러 발생함 (shape이 같아야 함) ex) reshape(4,4)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.36406828 0.63453448 0.92574772 0.64993591 0.25117511]
 [0.23737832 0.08403236 0.8271494  0.98516052 0.04173993]
 [0.58224921 0.60547371 0.11440811 0.44808003 0.67031556]]


#### 연산 함수
  - add, subtract, multiply, divide

In [4]:
np.add(x, y)  

array([[ 0.36406828,  1.63453448,  2.92574772,  3.64993591,  4.25117511],
       [ 5.23737832,  6.08403236,  7.8271494 ,  8.98516052,  9.04173993],
       [10.58224921, 11.60547371, 12.11440811, 13.44808003, 14.67031556]])

In [5]:
np.subtract(x, y)

array([[-0.36406828,  0.36546552,  1.07425228,  2.35006409,  3.74882489],
       [ 4.76262168,  5.91596764,  6.1728506 ,  7.01483948,  8.95826007],
       [ 9.41775079, 10.39452629, 11.88559189, 12.55191997, 13.32968444]])

In [6]:
np.multiply(x, y)

array([[0.        , 0.63453448, 1.85149545, 1.94980774, 1.00470045],
       [1.18689159, 0.50419415, 5.79004582, 7.88128417, 0.37565933],
       [5.82249206, 6.6602108 , 1.37289727, 5.82504037, 9.38441779]])

In [7]:
np.divide(x, y)

array([[  0.        ,   1.57595848,   2.16041579,   4.61583971,
         15.92514461],
       [ 21.0634233 ,  71.40106637,   8.46280004,   8.12050404,
        215.62089044],
       [ 17.17477652,  18.16759314, 104.88767342,  29.01267447,
         20.88568564]])

In [8]:
x+y

array([[ 0.36406828,  1.63453448,  2.92574772,  3.64993591,  4.25117511],
       [ 5.23737832,  6.08403236,  7.8271494 ,  8.98516052,  9.04173993],
       [10.58224921, 11.60547371, 12.11440811, 13.44808003, 14.67031556]])

In [9]:
x-y

array([[-0.36406828,  0.36546552,  1.07425228,  2.35006409,  3.74882489],
       [ 4.76262168,  5.91596764,  6.1728506 ,  7.01483948,  8.95826007],
       [ 9.41775079, 10.39452629, 11.88559189, 12.55191997, 13.32968444]])

In [10]:
x*y

array([[0.        , 0.63453448, 1.85149545, 1.94980774, 1.00470045],
       [1.18689159, 0.50419415, 5.79004582, 7.88128417, 0.37565933],
       [5.82249206, 6.6602108 , 1.37289727, 5.82504037, 9.38441779]])

In [11]:
x/y

array([[  0.        ,   1.57595848,   2.16041579,   4.61583971,
         15.92514461],
       [ 21.0634233 ,  71.40106637,   8.46280004,   8.12050404,
        215.62089044],
       [ 17.17477652,  18.16759314, 104.88767342,  29.01267447,
         20.88568564]])

#### 통계 함수
  - 평균, 분산, 중앙, 최대 , 최소값 등 통계 관련된 함수가 내장됨

In [18]:
print(y)

[[0.36406828 0.63453448 0.92574772 0.64993591 0.25117511]
 [0.23737832 0.08403236 0.8271494  0.98516052 0.04173993]
 [0.58224921 0.60547371 0.11440811 0.44808003 0.67031556]]


In [13]:
np.mean(y)  # 평균

0.4947632435286178

In [14]:
y.mean()  # 평균

0.4947632435286178

In [ ]:
np.max(y)

0.9224578856434428

In [19]:
np.argmax(y)    # 가장 큰 값의 인덱스를 가져옴

8

In [21]:
np.var(y), np.median(y), np.std(y)    # 분산, 중앙, 표준편차 계산

(0.08630027560580898, 0.5822492063399693, 0.29376908551753533)

#### 집계 함수
  - 합(sum), 누적 합계(cumsum) 등등 계산 가능

In [22]:
y

array([[0.36406828, 0.63453448, 0.92574772, 0.64993591, 0.25117511],
       [0.23737832, 0.08403236, 0.8271494 , 0.98516052, 0.04173993],
       [0.58224921, 0.60547371, 0.11440811, 0.44808003, 0.67031556]])

In [23]:
sum(y)

array([1.18369581, 1.32404055, 1.86730523, 2.08317646, 0.9632306 ])

In [25]:
np.sum(y, axis=0)   # 축을 따라 합을 구함 (행)

array([1.18369581, 1.32404055, 1.86730523, 2.08317646, 0.9632306 ])

In [26]:
np.sum(y, axis=1)   # 축을 따라 합을 구함 (열)

array([2.82546152, 2.17546053, 2.42052661])

In [28]:
np.sum(y, axis=None)    # None 이면 전체의 합을 구함

7.421448652929267

In [32]:
np.cumsum(y) # 누적 합계 

array([0.36406828, 0.99860277, 1.92435049, 2.57428641, 2.82546152,
       3.06283984, 3.1468722 , 3.9740216 , 4.95918212, 5.00092205,
       5.58317125, 6.18864496, 6.30305307, 6.7511331 , 7.42144865])

#### any, all 함수 
  - any : 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
  - all : 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [35]:
z = np.random.randn(10)
print(z)

[ 0.54097285 -0.91912881  1.46341301 -0.35092     1.60286895  1.02830761
  1.13465274  0.87479598  0.1928037   0.44569827]


In [36]:
z > 0 

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True])

In [39]:
np.any(z > 0)

True

In [38]:
np.all(z > 0)   # loop가 필요 없음

False

In [40]:
np.all(z !=0)

True

#### where 함수
  - 조건에 따라 선별적으로 값을 선택 가능
  - 예) 음수인 경우는 0, 나머지는 그대로 값을 쓰는 경우 

In [41]:
z = np.random.randn(10)
print(z)

[-0.19221178 -0.5343797   0.2534363  -0.82827537 -0.76251114  1.37231524
 -0.92635933  2.14317639 -0.23199022  1.79255228]


In [43]:
np.where(z > 0, z, 0)

array([0.        , 0.        , 0.2534363 , 0.        , 0.        ,
       1.37231524, 0.        , 2.14317639, 0.        , 1.79255228])