In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 nd array에 대한 연산은 각각의 원소별로 진행
  - 연산되는 두 ndarray가 서로 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 적용

#### 브로드캐스팅 Rule
  - [공식문서](https://numpy.org/doc/stable/_images/broadcasting_2.png)
  - 뒷 차원에서부터 비교하여 Shape가 같거나, 차원 중 값이 1인 것이 존재하면 가능

* Shape이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.82087839 0.06633895 0.97895431 0.05090279 0.5552826 ]
 [0.96950028 0.4242521  0.60649001 0.55184635 0.90573136]
 [0.75701666 0.81691903 0.06722116 0.58120558 0.31237174]]


In [3]:
x + y 

array([[ 0.82087839,  1.06633895,  2.97895431,  3.05090279,  4.5552826 ],
       [ 5.96950028,  6.4242521 ,  7.60649001,  8.55184635,  9.90573136],
       [10.75701666, 11.81691903, 12.06722116, 13.58120558, 14.31237174]])

* Scalar(상수)와의 연산

In [4]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [5]:
x **2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [6]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [7]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]


In [8]:
a + b   # b가 stretch되어 연산이 가능해짐

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [10]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)   # 3행짜리 벡터
c = np.arange(1000, 1004)   # 4행짜리 벡터

print(a)
print(b)
print(c)

print(a.shape)
print(b.shape)
print(c.shape)
                        # 브로드캐스팅은 뒷 차원에서부터 비교함
                        # (4,3)과 (3, )은 뒷 차원이 같음 
                        # (4, )와 (4, )은 뒷 차원이 다름 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
(4, 3)
(3,)
(4,)


In [16]:
# a + c   # shape이 안맞음

In [12]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)   # 3행짜리 벡터
c = np.arange(1000, 1004)   # 4행짜리 벡터

d = b.reshape(1,3)    # 1행 3열의 행렬

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(d)


(4, 3)
(3,)
(4,)
(1, 3)
[[100 101 102]]


In [14]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [15]:
a + b # b가 streth되어 연산 가능

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [19]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)  
d = b.reshape(1,3) 

