#### Boolean indexing
  - ndarray 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링
  - 예) 짝수인 경우만 찾아보기


In [1]:
import numpy as np

In [6]:
x = np.random.randint(1, 100, size=10)
print(x)

[73 23 85 47 69 57  6 58 92 51]


In [9]:
even_mask = x % 2 == 0
print(even_mask)

[False False False False False False  True  True  True False]


* bool 리스트를 인덱스로 전달

In [11]:
x[even_mask]

array([ 6, 58, 92])

In [12]:
x[x % 2 == 0]

array([ 6, 58, 92])

In [13]:
x[x > 80]

array([85, 92])

#### 다중조건 사용하기
  - 파이썬의 논리 연산자 and, or, not 키워드 사용 불가
  - &, | 사용

In [16]:
x % 2 == 0
x > 80

x[(x % 2 == 0) & (x > 80)]

array([92])

In [17]:
x < 30
x > 50 
x[(x < 30) | (x > 50)]

array([73, 23, 85, 69, 57,  6, 58, 92, 51])

예) 2023년 7월 서울 평균 기온 데이터 
  - 평균 기온이 25도를 넘는 날은 몇 일인가?
  - 평균 기온이 25도를 넘는 날의 평균 기온은 몇 도인가?

In [21]:
temp = np.array(
    [23.9, 24.4, 24.1, 25.4, 27.6, 29.7, 
     26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
     24.9, 25.9, 23.8, 24.7, 25.9, 26.9,
     28.6, 28.0, 25.1, 26.7, 28.1, 26.5,
     26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8]
)

In [23]:
len(temp)

31

In [24]:
temp[temp>25.0]

array([25.4, 27.6, 29.7, 26.7, 25.1, 25.9, 25.9, 26.9, 28.6, 28. , 25.1,
       26.7, 28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [26]:
len(temp[temp>25.0])

21

In [27]:
np.sum(temp>25.0)

21

In [28]:
np.mean(temp[temp>25.0])

26.87142857142857