In [1]:
import numpy as np

- Matrix
$$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix} 
\begin{pmatrix} x \\ y \end{pmatrix} = 
\begin{pmatrix} 25 \\ 64 \end{pmatrix}$$

- Vector
  - 행(row vector) 또는 열(column vector)의 수가 1인 경우

- 역행렬 (Inverse)
  - 아래를 만족할 때 B는 A의 역행렬이고 A는 B의 역행렬이다.
  - AB = BA = E(단위행렬)


#### numpy.linalg.inv
- 역행렬을 구할 때 사용하는 함수
- 모든 차원의 값이 같아야함


In [12]:
x = np.random.rand(3,3)     #정사각 행렬만 가능
print(x)

np.linalg.inv(x)      #역행렬을 구할 수 있는 경우는 정사각 행렬의 경우만 가능

[[0.04209329 0.37130677 0.0837487 ]
 [0.56258698 0.46720916 0.64403602]
 [0.35995617 0.70927006 0.19495102]]


array([[-7.41904273, -0.26344476,  4.05744542],
       [ 2.47795698, -0.44508126,  0.40585929],
       [ 4.68317383,  2.10571548, -3.83874046]])

In [14]:
x @ np.linalg.inv(x)

array([[ 1.00000000e+00, -4.05011500e-17,  1.07417657e-16],
       [-1.25374933e-16,  1.00000000e+00,  6.58152425e-17],
       [-3.06226026e-16, -6.06695313e-18,  1.00000000e+00]])

In [16]:
np.matmul(x, np.linalg.inv(x))

array([[ 1.00000000e+00, -4.05011500e-17,  1.07417657e-16],
       [-1.25374933e-16,  1.00000000e+00,  6.58152425e-17],
       [-3.06226026e-16, -6.06695313e-18,  1.00000000e+00]])

In [19]:
x = np.random.rand(3,3,3)
np.linalg.inv(x)

array([[[  1.85366187,   5.10153186,  -4.3910616 ],
        [  0.90941805,  -1.40742676,   1.03599815],
        [ -1.63483948,  -2.15917456,   3.44459849]],

       [[-17.02031718,   7.89905137,  -0.05419971],
        [ -1.98491007,  -0.40766304,   1.32338657],
        [ 21.87955874,  -7.88489154,  -0.49255626]],

       [[ -0.26325829,   6.93999146,  -7.54289701],
        [ -0.58328897,   0.70220797,   0.77491579],
        [  2.78903958,  -9.25790642,   8.43269299]]])

In [21]:
x @ np.linalg.inv(x)

array([[[ 1.00000000e+00,  3.94540437e-17, -2.52596315e-16],
        [-2.80231693e-17,  1.00000000e+00,  2.54735068e-18],
        [-2.23631463e-16, -3.89486347e-16,  1.00000000e+00]],

       [[ 1.00000000e+00, -1.75970074e-16,  1.71340265e-18],
        [-1.11073864e-17,  1.00000000e+00,  2.33791359e-17],
        [-1.29548502e-15, -1.05518605e-15,  1.00000000e+00]],

       [[ 1.00000000e+00, -2.79846328e-17, -5.36453688e-17],
        [ 8.99097028e-17,  1.00000000e+00, -5.27529888e-17],
        [ 5.51948446e-17, -1.43890493e-16,  1.00000000e+00]]])

####**numpy.linalg.solve**
- Ax = B 형태의 선형대수식 솔루션을 제공하는 함수
- 예) x와 y의 합은 25
      2x와 4y의 합은 64

In [31]:
A = np.array([[1,1],[2,4]])
B = np.array([[25],[64]])

x = np.linalg.solve(A,B)

print(x)

[[18.]
 [ 7.]]


In [33]:
np.allclose(A@x, B)     # 두 수를 비교하는 함수

True