In [1]:
import numpy as np

In [5]:
def generate_lotto_nums():
  return np.random.choice(np.arange(1, 46), size=6, replace=False) 

generate_lotto_nums()

array([16, 35,  7, 39, 20, 21])

2. numpy 이용하여 pi(원주율)값을 출력하시오.
  - 몬테카를로 방법을 이용 => 난수를 발생시켜 어떤 특정한 값(pi)의 근사값을 구하는 것

In [6]:
# 다트를 던졌을 때  전체 원 면적(pi = 1^2)에서 해당 그림처럼 들어갈 수 있는 경우 (pi * 1^2 / 4)의 확률
# (비례식) pi/4 : 1 = 4분원 안에 생성된 점 갯수 : 전체 시도 횟수 (천만번, 1e7)
# pi/4 * 1e7 = 4분원 안에 생성된 점 갯수
# pi/4 = 4분원 안에 생성된 점 갯수 / 1e7
# pi = 4 * 4분원 안에 생성된 점 갯수 / 1e7  

In [8]:
total = int(1e7)
points = np.random.rand(total, 2)
print(points)
points.shape

[[0.83875182 0.17724669]
 [0.37053657 0.56545216]
 [0.254961   0.228588  ]
 ...
 [0.2061218  0.21423566]
 [0.09232268 0.70420209]
 [0.11438699 0.58572086]]


(10000000, 2)

In [9]:
# 위 천만개 points 중 어떤 것이 그림의 원호 안에 있는 것인지 알아야 함
# 우리는 원호 안에 있는 것만 필요함
# 원의 방정식에 의해서 x^2 + y^ <= 1 => 원호 안에 있는 것 

In [12]:
np.sum(points ** 2, axis = 1) # 각각의 제곱의 합 ,  열 단위로 더함

array([0.734921  , 0.45703349, 0.11725758, ..., 0.08838311, 0.50442406,
       0.35615331])

In [13]:
np.sum(points ** 2, axis =1) <1 # 천만개 중에서 원안에 들어가는 것만 구하기 위해서 1보다 작은거만 구함 (False는 1보다 큼)

array([ True,  True,  True, ...,  True,  True,  True])

In [15]:
np.sum(np.sum(points ** 2, axis =1) <1) # True 개수를 구함, 전체 천만개 중에서 4분위 호 안에 들어간 points 수

7853935

In [16]:
# pi = 4 * 4분원 안에 생성된 점 개수 / 1e7
4 * np.sum(np.sum(points ** 2, axis =1) <1) /total # pi의 근사치 구함

3.141574