In [1]:
import numpy as np

#### np.array 함수로 생성하기

In [5]:
x = np.array([1,2,3,4])
print(x)

y = np.array([[2,3,4],[1,2,5]])   # 2행 3열의 행렬 생성
print(y)

print(type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>


#### np.arrange 함수로 생성하기

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10) # python의 range()와 비슷한 기능

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
# 5에서 100까지 간격 5인 ndarray 생성
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, np.zeros로 ndarray 생성하기

In [14]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((2,3,4))    # 3행 4열 행렬이 2개가 생성됨 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
np.zeros((2,3,6,6))

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [

#### np.empty.np.full로 ndarray 생성하기

In [20]:
np.empty((3,4))   # 특정값으로 초기화 되지 않음, 임의의 값으로 채워짐

array([[3.0968256e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [21]:
np.full((3,4,2),7)

array([[[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]]])

#### np.eye로 ndarray 생성하기
  - 단위 행렬 생성

In [24]:
np.eye(3)   # 3의 3월 행렬을 만들며 대각선은 1로 생성함

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.linspace로  ndarray 생성하기

In [26]:
np.linspace(1, 10, 3)     # 1부터 10 사이의 3개의 수를 생성하는데, 그 간격이 일정하게 만들어라

array([ 1. ,  5.5, 10. ])

In [28]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [29]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### reshape 함수 사용
  - ndarray의 형태, 차원을 바꾸기 위해 사용

In [37]:
x = np.arange(1,16)
print(x) 

x.shape   # 튜플로 표시됨, 1차원이니까 1개로만 표시됨 

x.reshape(3,5)
x.reshape(5,3)
x.reshape(5,3,1)

# x.reshape(5,4) #숫자가 최소한 20개는 있어야 함, 그러나 현재 x는 15개 밖에 없기 때문에 에러가 발생했음


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])